<html><head></head><body><section data-pdf-bookmark="Chapter 12. Exception Handling: Putting out Fires Gets old" data-type="chapter" epub:type="chapter"><div class="chapter" id="exception_handling_putting_out_fires_get">&#13;
<h1><span class="label">Chapter 12. </span>Exception Handling: <em>Putting out Fires Gets old</em></h1>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg623.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p><a data-primary="exception handling" data-secondary="about" data-type="indexterm" id="idm46402338275352"/><strong>Programmers aren’t meant to be firefighters.</strong></p>&#13;
<p>You’ve worked your tail off, wading through technical manuals and a few engaging <em>Head First</em> books, and you’ve reached the pinnacle of your profession. But you’re still getting panicked phone calls in the middle of the night from work because <strong>your program crashes</strong>, or <strong>doesn’t behave like it’s supposed to</strong>. Nothing pulls you out of the programming groove like having to fix a strange bug...but with <strong>exception handling</strong>, you can write code to <strong>deal with problems</strong> that come up. Better yet, you can even plan for those problems, and <strong>keep things running</strong> when they happen.</p>&#13;
<section data-pdf-bookmark="Your hex dumper reads a filename from the command line" data-type="sect1"><div class="sect1" id="your_hex_dumper_reads_a_filename_from_th">&#13;
<h1>Your hex dumper reads a filename from the command line</h1>&#13;
<p><a data-primary="command line" data-type="indexterm" id="idm46402338268552"/><a data-primary="hex dump" data-type="indexterm" id="idm46402338267176"/>At the end of <a href="ch10.html#reading_and_writing_files_save_the_last">#reading_and_writing_files_save_the_last</a> you built a hex dumper that uses command-line arguments to dump any file. You used the project properties in the IDE to set the arguments for the debugger, and you saw how to call it from a Windows command prompt or macOS Terminal window.</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg624-1.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<section data-pdf-bookmark="But what happens if you give HexDump an invalid filename?" data-type="sect2"><div class="sect2" id="but_what_happens_if_you_give_hexdump_an">&#13;
<h2>But what happens if you give HexDump an invalid filename?</h2>&#13;
<p>When you modified your HexDump app to use command-line arguments, we asked you to be careful to specify a valid filename. What happens when you give it an invalid filename? Try running your app again from the command line, but this time give it the argument <strong><code>invalid-filename</code></strong>. Now it <strong><em>throws an exception.</em></strong></p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg624-2.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p>Use the project settings to set the program’s argument to an invalid filename and run the app in the IDE’s debugger. Now you’ll see it throw an exception with the same class name (System.IO.FileNotFoundException) and a similar “Could not find file” message.</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg624-3.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="sharpen_your_pencil-idd0041">&#13;
<h5><span class="inlineimage"><img alt="Images" src="assets/pencil.png"/></span> Sharpen your pencil</h5>&#13;
<p><a data-primary="exercises" data-secondary="Sharpen your pencil" data-tertiary="broken code" data-type="indexterm" id="idm46402338252072"/><a data-primary="Sharpen Your Pencil exercises" data-secondary="broken code" data-type="indexterm" id="idm46402338250744"/><strong>This code is broken.</strong> The code throws five different exceptions, and the error messages you’ll see in the IDE or the console are on the right. It’s your job to <strong>match the line of code</strong> that has a problem with the <strong>exception that line generates</strong>. Read the exception messages for hints. Keep in mind that <strong><em>this code <u>does not work</u></em></strong>. If you add this class to an app and run its Main method, it will halt after the first exception is thrown. Just read through the code and match each exception to the line that <em>would</em> throw it if it ran.</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg625.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
</div></aside>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="sharpen_your_pencil_solution-idd024">&#13;
<h5><span class="inlineimage"><img alt="Images" src="assets/pencil.png"/></span> Sharpen your pencil Solution</h5>&#13;
<p>Your job was to match each line of code that has a problem with the exception that line generates.</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg626.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
</div></aside>&#13;
<div data-type="note" epub:type="note"><h6>Note</h6>&#13;
<p><strong>You’d never actually get all these exceptions in a row—the program would throw the first exception and then halt. You’d only get to the second exception if you fixed the first.</strong></p>&#13;
</div>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="sharpen_your_pencil_solution-idd025">&#13;
<h5><span class="inlineimage"><img alt="Images" src="assets/pencil.png"/></span> Sharpen your pencil Solution</h5>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg627-1.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg627-2.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p><a data-primary="DivideByZeroException" data-type="indexterm" id="idm46402338232296"/><a data-primary="errors" data-secondary="DivideByZero" data-type="indexterm" id="idm46402338231144"/><a data-primary="exception handling" data-secondary="DivideByZeroException" data-type="indexterm" id="idm46402338229960"/><a data-primary="exception handling" data-secondary="dividing any number by zero" data-type="indexterm" id="idm46402338228840"/><a data-primary="exception handling" data-secondary="NullReferenceException" data-type="indexterm" id="idm46402338227768"/><a data-primary="NullReferenceException (NRE)" data-type="indexterm" id="idm46402338226616"/><strong>That DivideByZero error didn’t have to happen.</strong></p>&#13;
<p>You can see just by looking at the code that there’s something wrong. If you think about it, the same goes for the other exceptions—this whole “Sharpen your pencil” exercise was about spotting those exceptions without running the code. Every one of those exceptions was <strong><em>preventable</em></strong>. The more you know about exceptions, the better you’ll be at keeping your apps from crashing.</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg627-3.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
</div></aside>&#13;
</div></section>&#13;
</div></section>&#13;
<section data-pdf-bookmark="When your program throws an exception, the CLR generates an Exception object" data-type="sect1"><div class="sect1" id="when_your_program_throws_an_exceptioncom">&#13;
<h1>When your program throws an exception, the CLR generates an <u>Exce</u>p<u>tion</u> object</h1>&#13;
<p><a data-primary="CLR (Common Language Runtime)" data-type="indexterm" id="idm46402338219768"/><a data-primary="exception handling" data-type="indexterm" id="idm46402338218888"/><a data-primary="exception handling" data-secondary="Exception object generated when program throws exception" data-type="indexterm" id="idm46402338218040"/><a data-primary="IndexOutOfRangeException" data-type="indexterm" id="idm46402338216952"/>You’ve been looking at the CLR’s way of telling you something went wrong in your program: an <strong>exception</strong>. When an exception occurs in your code, an object is created to represent the problem. It’s called—no surprise here—Exception.</p>&#13;
<p>For example, suppose you have an array with four items, and you try to access the 16th item (index 15, since we’re zero-based here):</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg628.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<div data-type="note" epub:type="note"><h6>Note</h6>&#13;
<p>ex-cep-tion, noun.</p>&#13;
<p>a person or thing that is excluded from a general statement or does not follow a rule. <em>While Jamie usually hates peanut butter, they made an <strong>exception</strong> for Parker’s peanut butter fudge.</em></p>&#13;
</div>&#13;
<p>When the IDE halts because the code threw an exception, you can see the details of the exception by <strong>expanding</strong> <strong><code>$exception</code></strong> <strong>in the Locals window</strong>. The Locals window shows you all of the variables currently <strong><em>in scope</em></strong> (which means the current statement has access to them).</p>&#13;
<p>The CLR goes to the trouble of creating an object because it wants to give you all the information it has about what caused the exception. You may have code to fix, or you may just need to make some changes to how you handle a particular situation in your program.</p>&#13;
<p>This particular exception is an <strong>IndexOutOfRangeException</strong>, which gives you an idea of what the problem is: you’re trying to access an index in the array that’s out of range. You’ve also got information about exactly where in the code the problem occurred, making it easier to track down and solve (even if you’ve got thousands of lines of code).</p>&#13;
</div></section>&#13;
<section data-pdf-bookmark="All Exception objects inherit from System.Exception" data-type="sect1"><div class="sect1" id="all_exception_objects_inherit_from_syste">&#13;
<h1>All Exception objects inherit from System.Exception</h1>&#13;
<p><a data-primary="DivideByZeroException" data-type="indexterm" id="idm46402338201272"/><a data-primary="exception handling" data-type="indexterm" id="idm46402338200536"/><a data-primary="exception handling" data-secondary="DivideByZeroException" data-type="indexterm" id="idm46402338206168"/><a data-primary="exception handling" data-secondary="FormatException" data-type="indexterm" id="idm46402338205064"/><a data-primary="exception handling" data-secondary="IndexOutOfRangeException" data-type="indexterm" id="idm46402338199720"/><a data-primary="exception handling" data-secondary="OverFlowException" data-type="indexterm" id="idm46402338198632"/><a data-primary="FormatException" data-type="indexterm" id="idm46402338197512"/><a data-primary="IndexOutOfRangeException" data-type="indexterm" id="idm46402338196632"/><a data-primary="Message property, Exception object" data-type="indexterm" id="idm46402338195800"/><a data-primary="OverFlowException" data-type="indexterm" id="idm46402338195064"/>.NET has lots of different exceptions it may need to report. Since many of these have a lot of similar features, inheritance comes into play. .NET defines a base class, called Exception, that all specific exception types inherit from.</p>&#13;
<p>The Exception class has a couple of useful members. The Message property stores an easy-to-read message about what went wrong. StackTrace tells you what code was being executed when the exception occurred, and what led up to the exception. (There are others, too, but we’ll use those first.)</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg629.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="brain_power-idd0028">&#13;
<h5><span class="inlineimage"><img alt="Images" src="assets/brainpower.png"/></span> Brain Power</h5>&#13;
<p>Your HexDump app throws an exception if you pass it an invalid filename on the command line. What can you do to deal with that problem?</p>&#13;
</div></aside>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="sleuth_it_out-idd0005">&#13;
<h5><span class="inlineimage"><img alt="Images" src="assets/cap.png"/></span> Sleuth it out</h5>&#13;
<p>The first step in troubleshooting any exception is taking a really close look at all of the information that it gives you. When you’re running a console app, that information is written to the console. Let’s take a closer look at the diagnostic information our app printed (we moved our app to the C:\HexDump folder to make the paths in this stack trace shorter):</p>&#13;
<pre data-type="programlisting">C:\HexDump\bin\Debug\netcoreapp3.1&gt; <strong>HexDump invalid-filename</strong>&#13;
Unhandled exception. System.IO.FileNotFoundException: Could not find file ’C:\HexDump\bin\Debug\&#13;
netcoreapp3.1\invalid-filename’.&#13;
File name: ’C:\HexDump\bin\Debug\netcoreapp3.1\invalid-filename’&#13;
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)&#13;
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)&#13;
   at System.IO.FileStream..ctor(String path, FileMode mode, ... , FileOptions options)&#13;
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)&#13;
   at System.IO.File.OpenRead(String path)&#13;
   at HexDump.Program.Main(String[] args) in C:\HexDump\Program.cs:line 12</pre>&#13;
<p>Here’s what we noticed:</p>&#13;
<ul>&#13;
<li><p>The exception class: <code>System.IO.FileNotFoundException</code></p></li>&#13;
<li><p>The exception message: <code>Could not find file ’C:\HexDump\bin\Debug\netcoreapp3.1\invalid-filename’.</code></p></li>&#13;
<li><p>Additional diagnostic information: <code>File name: ’C:\HexDump\bin\Debug\netcoreapp3.1\invalid-filename’</code></p></li>&#13;
<li><p>The first five lines in the stack trace come from classes in the System.IO namespace.</p></li>&#13;
<li><p>The last line of the stack trace is in our namespace, HexDump—and it includes a line number. Here’s what’s on that line: <code>using (Stream input = File.OpenRead(args[0]))</code></p></li>&#13;
</ul>&#13;
<p><strong>Reproduce the exception in the debugger</strong></p>&#13;
<p>At the end of <a href="ch10.html#reading_and_writing_files_save_the_last">#reading_and_writing_files_save_the_last</a> we showed you how to set the application arguments when you run an app in the debugger. Set the arguments to <code>invalid-filename</code>, then place a breakpoint on the line in the app that’s throwing the exception. Run the app, then when you get to the breakpoint step over that statement. You should see the exception in the IDE.</p>&#13;
<p><strong>Add code to <u>prevent</u> the exception</strong></p>&#13;
<div data-type="note" epub:type="note"><h6>Note</h6>&#13;
<p><span style="color:#9D9EA0;">If you’re running from the command line on your Mac, don’t forget to republish it by running “dotnet publish -r osx-x64” from the solution folder.</span></p>&#13;
</div>&#13;
<p>The app is throwing an exception because it’s trying to read a file that doesn’t exist. So let’s <strong><em>prevent</em></strong> this exception from happening by checking if the file exists first. If it doesn’t, instead of using File.OpenRead to open a stream with the contents of the file, we’ll use Console.OpenStandardInput, which returns a stream of your app’s <strong>standard input</strong> (or <strong>stdin</strong>). Start by <strong>adding this GetInputStream method</strong> to your app:</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg630.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p>Then modify the line of the app that throws the exception to call the new method:</p>&#13;
<pre data-type="programlisting">        using (Stream input = <strong>GetInputStream(args))</strong></pre>&#13;
<p>Now run your app in the IDE. It doesn’t throw an exception. Instead, it’s reading from standard input. Test it out:</p>&#13;
<ul>&#13;
<li><p>Type some data and press Enter—it will show a hex dump of everything you typed, ending with a return (<code>0d 0a</code> on Windows, <code>0a</code> on Mac). The stdin stream only adds data after a return, so the app will do a new dump for each line.</p></li>&#13;
<li><p>Run your app from the command line: <code>HexDump &lt;&lt; input.txt</code> (or <code>./HexDump &lt;&lt; input.txt</code> on a Mac).The app will pipe data from <em>input.txt</em> into the stdin stream and dump all of the bytes in the file.</p></li>&#13;
</ul>&#13;
</div></aside>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="there_are_no_dumb_questions-idd0040">&#13;
<h5>there are no Dumb Questions</h5>&#13;
<p><a data-primary="CLR (Common Language Runtime)" data-type="indexterm" id="idm46402338159688"/><a data-primary="exception handling" data-type="indexterm" id="idm46402338158664"/><a data-primary="exception handling" data-secondary="using exceptions to find bugs" data-type="indexterm" id="idm46402338157816"/><strong>Q: What <strong><em>is</em></strong> an exception, really?</strong></p>&#13;
<p><strong>A:</strong> It’s an object that the CLR creates when there’s a problem. You can specifically generate exceptions in your code, too—in fact, you’ve done that already using the <code>throw</code> keyword.</p>&#13;
<p><strong>Q:</strong> <strong>An exception is an</strong> <strong><em>object?</em></strong></p>&#13;
<p><strong>A:</strong> Yes, an exception is an object. The CLR generates it to give you as much information as it can about exactly what was going on when it executed the statement that threw the exception. Its properties—which you saw when you expanded <code>$exception</code> in the Locals window—tell you information about the exception. For example, its Message property will have a useful string like <em>Attempted to divide by zero</em> or <em>Value was either too large or too small for an Int.32</em>.</p>&#13;
<p><strong>Q: Why are there so many types of Exception objects?</strong></p>&#13;
<p><strong>A:</strong> Because there are so many ways that your code can act in unexpected ways. There are a lot of situations that will cause your code to simply crash. It would be really hard to troubleshoot the problems if you didn’t know why the crash happened. By throwing different kinds of exceptions under different circumstances, the CLR is giving you a lot of really valuable information to help you track down and correct the problem.</p>&#13;
<p><strong>Q: Does that mean that when my code throws an exception, it’s not necessarily because I did something wrong?</strong></p>&#13;
<p><strong>A:</strong> Exactly. Sometimes your data’s different than you expected it to be, like in the example where we had a statement working with an array that was a lot shorter than anticipated. Also, don’t forget that real, live, actual human beings are using your program, and they’ll often act in unpredictable ways. Exceptions are C#’s way to help you handle those unexpected situations so that your code still runs smoothly and doesn’t simply crash or give a cryptic, useless error message.</p>&#13;
<p><strong>Q: So exceptions are there to help me, not just cause me grief and force me to track down frustrating bugs at 3:00 AM?</strong></p>&#13;
<p><strong>A:</strong> Yes! Exceptions are all about helping you expect the unexpected. A lot of people get frustrated when they see code throw an exception. Instead, think about them as C#’s way of helping you track down problems and debug your programs.</p>&#13;
</div></aside>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg631.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p><strong>That’s right. Exceptions are a really useful tool that you can use to find places where your code acts in <span style="color:#9D9EA0;">ways you don’t expect.</span></strong></p>&#13;
<p>A lot of programmers get frustrated the first time they see an exception. But exceptions are really useful, and you can use them to your advantage. When you see an exception, it’s giving you a lot of clues to help you figure out why your code is reacting in a way that you didn’t anticipate. That’s good for you: it lets you know about a new scenario that your program has to handle, and it gives you an opportunity to <strong>do something about it.</strong></p>&#13;
<blockquote>&#13;
<p><strong>Exceptions are all about helping you find and fix situations where your code behaves in ways you didn’t expect.</strong></p>&#13;
</blockquote>&#13;
</div></section>&#13;
<section data-pdf-bookmark="There are some files you just can’t dump" data-type="sect1"><div class="sect1" id="there_are_some_files_you_just_canapostro">&#13;
<h1>There are some files you just can’t dump</h1>&#13;
<p>In <a href="ch09.html#linq_and_lambdas_get_control_of_your_dat">#linq_and_lambdas_get_control_of_your_dat</a> we talked about making your code <strong>robust</strong> so that it can deal with bad data, malformed input, user errors, and other unexpected situations. Dumping stdin if no file is passed on the command line or if the file doesn’t exist is a great start to making the hex dumper robust.</p>&#13;
<p>But are there still  some cases that we need to handle? For example, what if the file exists but it’s not readable? Let’s see what happens if we remove read access from a file, then try to read it:</p>&#13;
<ul>&#13;
<li><p><strong><em>On Windows:</em></strong> Right-click the file in the Windows Explorer, go to the Security tab, and click Edit to change the permissions. Check all of the Deny boxes.</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg632-1.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
</li>&#13;
<li><p><strong><em>On a Mac:</em></strong> In a Terminal window, change to the folder with the file you want to dump, and run this command, replacing <code>binarydata.dat</code> with the name of your file): <code>chmod 000 binarydata.dat.</code></p></li>&#13;
</ul>&#13;
<p>Now that you’ve removed read permissions from your file, try running your app again, either in the IDE or from the command line.</p>&#13;
<p>You’ll see an exception—the stack trace shows that the <strong><code>using</code> statement called the GetInputStream method</strong>, which eventually caused the FileStream to throw a System.UnauthorizedAccessException:</p>&#13;
<pre data-type="programlisting">C:\HexDump\bin\Debug\netcoreapp3.1&gt;hexdump binarydata.dat&#13;
Unhandled exception. <strong>System.UnauthorizedAccessException: Access to the path ’C:\HexDump\bin\Debug\&#13;
netcoreapp3.1\binarydata.dat’ is denied.</strong>&#13;
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)&#13;
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, ..., FileOptions options)&#13;
   at System.IO.FileStream..ctor(String path, ..., Int32 bufferSize, FileOptions options)&#13;
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)&#13;
   at System.IO.File.OpenRead(String path)&#13;
   at HexDump.Program.GetInputStream(String[] args) in <strong>C:\HexDump\Program.cs:line 14</strong>&#13;
   at HexDump.Program.Main(String[] args) in <strong>C:\HexDump\Program.cs:line 20</strong></pre>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg632-2.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p><strong>Actually, there <span style="color:#9D9EA0;"><u><em>is</em></u></span> something you can do about it.</strong></p>&#13;
<p>Yes, users do, indeed, screw up all the time. They’ll give you bad data, weird input, click on things you didn’t even know existed. That’s a fact of life, but that doesn’t mean you can’t do anything about it. C# gives you really useful <strong>exception handling tools</strong> to help you make your programs more robust. Because while you <em>can’t</em> control what your users do with your app, you <em>can</em> make sure that your app doesn’t crash when they do it.</p>&#13;
</div></section>&#13;
<section data-pdf-bookmark="What happens when a method you want to call is risky?" data-type="sect1"><div class="sect1" id="what_happens_when_a_method_you_want_to_c">&#13;
<h1>What happens when a method you want to call is <u>risky</u>?</h1>&#13;
<p><a data-primary="methods" data-secondary="risk in calling" data-type="indexterm" id="idm46402338118568"/><a data-primary="risky code (LINQ)" data-type="indexterm" id="idm46402338117000"/><a data-primary="robust design" data-type="indexterm" id="idm46402338116264"/>Users are unpredictable. They feed all sorts of weird data into your program, and click on things in ways you never expected. That’s just fine, because you can deal with exceptions that your code throws by adding <strong>exception handling</strong>, which lets you write special code that gets executed any time an exception is thrown.</p>&#13;
<ol>&#13;
<li><p><strong>Let’s say a method called in your program takes input from a user.</strong></p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg633-1.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
</li>&#13;
<li><p><strong>That method could do something risky that might not work at <span style="color:#9D9EA0;"><u>runtime.</u></span></strong></p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg633-2.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg633-3.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
</li>&#13;
<li><p><strong>You need to know that the method you’re calling is risky.</strong></p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg633-4.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<div data-type="note" epub:type="note"><h6>Note</h6>&#13;
<p><span style="color:#9D9EA0;">If you can come up with a way to do a less risky thing that avoids throwing the exception, that’s the best possible outcome! But some risks just can’t be avoided, and that’s when you want to do this.</span></p>&#13;
</div></li>&#13;
<li><p><strong>You can then write code that can <u><em>handle</em></u> the exception if it does happen. You need to be prepared, just in case.</strong></p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg633-5.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
</li>&#13;
</ol>&#13;
</div></section>&#13;
<section data-pdf-bookmark="Handle exceptions with try and catch" data-type="sect1"><div class="sect1" id="handle_exceptions_with_try_and_catch">&#13;
<h1>Handle exceptions with try and catch</h1>&#13;
<p><a data-primary="catch blocks" data-secondary="about" data-type="indexterm" id="idm46402338096072"/><a data-primary="exception handling" data-secondary="catch block" data-type="indexterm" id="idm46402338094824"/><a data-primary="exception handling" data-secondary="try block" data-type="indexterm" id="idm46402338093784"/><a data-primary="try blocks" data-seealso="exception handling" data-type="indexterm" id="idm46402338092632"/>When you add exception handling to your code, you’re using the <code>try</code> and <code>catch</code> keywords to create a block of code that gets run if an exception is thrown.</p>&#13;
<p>Your <em>try/catch</em> code basically tells the C# compiler: “<strong>Try</strong> this code, and if an exception occurs, <strong>catch</strong> it with this <em>other</em> bit of code.” The part of the code you’re trying is the <code>try</code> <strong>block</strong>, and the part where you deal with exceptions is called the <code>catch</code> <strong>block</strong>. In the <code>catch</code> block, you can do things like print a friendly error message instead of letting your program come to a halt.</p>&#13;
<p>Let’s have another look at the last three lines of the stack trace in our HexDump scenario to help us figure out where to put our exception handling code:</p>&#13;
<pre data-type="programlisting">   at System.IO.<strong>File.OpenRead</strong>(String path)&#13;
   at HexDump.Program.<strong>GetInputStream</strong>(String[] args) in Program.cs:line 14&#13;
   at HexDump.Program.Main(String[] args) in Program.cs:line 20</pre>&#13;
<p>The UnauthorizedAccessException is caused by the line in GetInputStream that calls File.OpenRead. Since we can’t prevent that exception, let’s modify GetInputStream to use a <em>try/catch</em> block:</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg634.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p>We kept things simple in our exception handler. First we used Console.Error to write a line to the error output (stderr) letting the user know that an error occurred, then we fell back to reading data from standard input so the program still did something. Notice how <strong>the <code>catch</code> block has a <code>return</code> statement</strong>. The method returns a Stream, so if it handles an exception it still needs to return a Stream; otherwise you’ll get the “not all code paths return a value” compiler error.</p>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="brain_power-idd0029">&#13;
<h5><span class="inlineimage"><img alt="Images" src="assets/brainpower.png"/></span> Brain Power</h5>&#13;
<p>If throwing an exception makes your code automatically jump to the <code>catch</code> block, what happens to the objects and data you were working with before the exception happened?</p>&#13;
</div></aside>&#13;
</div></section>&#13;
<section data-pdf-bookmark="Use the debugger to follow the try/catch flow" data-type="sect1"><div class="sect1" id="use_the_debugger_to_follow_the_trysolidu">&#13;
<h1>Use the debugger to follow the try/catch flow</h1>&#13;
<p><a data-primary="catch blocks" data-secondary="following in debugger" data-type="indexterm" id="idm46402338074280"/><a data-primary="debugger" data-secondary="catch blocks" data-type="indexterm" id="idm46402338071576"/><a data-primary="debugger" data-secondary="following try/catch flow" data-type="indexterm" id="idm46402338070424"/><a data-primary="try blocks" data-seealso="exception handling" data-type="indexterm" id="idm46402338069352"/>An important part of exception handling is that when a statement in your <code>try</code> block throws an exception, the rest of the code in the block gets <strong>short-circuited</strong>. The program’s execution immediately jumps to the first line in the <code>catch</code> block. Let’s use the IDE’s debugger to explore how this works.</p>&#13;
<p><strong><em>Debug this!</em></strong></p>&#13;
<ol>&#13;
<li><p>Replace the GetInputStream method in your HexDump app with the one that we just showed you to handle an UnauthorizedAccessException.</p></li>&#13;
<li><p>Modify your project options to set the argument so that it contains the path to an unreadable file.</p></li>&#13;
<li><p>Place a breakpoint on the first statement in GetInputStream, then start debugging your project.</p></li>&#13;
<li><p>When it hits the breakpoint, step over the next few statements until you get to File.OpenRead. Step over it—the app jumps to the first line in the <code>catch</code> block.</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg635.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
</li>&#13;
<li><p>Keep stepping through the rest of the <code>catch</code> block. It will write the line to the console, then return Console.OpenStandardInput and resume the Main method.</p></li>&#13;
</ol>&#13;
</div></section>&#13;
<section data-pdf-bookmark="If you have code that ALWAYS needs to run, use a finally block" data-type="sect1"><div class="sect1" id="if_you_have_code_that_always_needs_to_ru">&#13;
<h1>If you have code that <u>ALWAYS</u> needs to run, use a finally block</h1>&#13;
<p><a data-primary="debugger" data-secondary="finally block" data-type="indexterm" id="idm46402338065224"/><a data-primary="exception handling" data-secondary="finally block" data-type="indexterm" id="idm46402338055304"/><a data-primary="finally block" data-type="indexterm" id="idm46402338054216"/>When your program throws an exception, a couple of things can happen. If the exception <strong><em>isn’t</em></strong> handled, your program will stop processing and crash. If the exception <strong><em>is</em></strong> handled, your code jumps to the <code>catch</code> block. What about the rest of the code in your <code>try</code> block? What if you were closing a stream, or cleaning up important resources? That code needs to run, even if an exception occurs, or you’re going to make a mess of your program’s state. That’s where you’ll use a <code><strong>finally block</strong></code>. It’s a block of code that comes after the <code>try</code> and <code>catch</code>. The <code><strong>finally</strong></code> block always runs, whether or not an exception was thrown. Let’s use the debugger to explore how the <code>finally</code> block works.</p>&#13;
<p><strong><em>Debug this!</em></strong></p>&#13;
<ol>&#13;
<li><p><strong>Create a new Console App project.</strong></p>&#13;
<p>Add <code>using System.IO;</code> to the top of the file, then add this Main method:</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg636.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<div data-type="note" epub:type="note"><h6>Note</h6>&#13;
<p><span style="color:#9D9EA0;">You’ll see the exception in the Locals window, just like you did earlier.</span></p>&#13;
</div>&#13;
</li>&#13;
<li><p><strong>Add a breakpoint to the first line of the Main method.</strong></p>&#13;
<p>Debug your app and step through it. The first line in the <code>try</code> block tries to access <code>args[0]</code>, but since you didn’t specify any command-line arguments the <code>args</code> array is empty and it throws an exception—specifically, a System.<strong>IndexOutOfRangeException</strong>, with the message <em>“Index was outside the bounds of the array.”</em> After it prints the message, it <strong>executes the</strong> <code><strong>finally</strong></code> <strong>block</strong>, and then the program exits.</p></li>&#13;
<li><p><strong>Set a command-line argument with the path of a <u>valid</u> file.</strong></p>&#13;
<p>Use the project properties to pass a command-line argument to the app. Give it the full path of a valid file. Make sure there are no spaces in the filename, otherwise the app will interpret it as two arguments. Debug your app again—after it finishes the <code>try</code> block, it <strong>executes the</strong> <code><strong>finally</strong></code> <strong>block.</strong></p></li>&#13;
<li><p><strong>Set a command-line argument with an <u>invalid file path.</u></strong></p>&#13;
<p>Go back to the project properties and change the command-line argument to pass the app the name of a file that <u>does not exist</u>. Run your app again. This time it catches a different exception: a System.IO.<strong>FileNotFoundException</strong>. Then it <strong>executes the <code>finally</code> block.</strong></p></li>&#13;
</ol>&#13;
</div></section>&#13;
<section data-pdf-bookmark="Catch-all exceptions handle System.Exception" data-type="sect1"><div class="sect1" id="catch_all_exceptions_handle_systemdotexc">&#13;
<h1>Catch-all exceptions handle System.Exception</h1>&#13;
<p><a data-primary="catch-all exceptions" data-type="indexterm" id="idm46402338028296"/><a data-primary="System.Exception" data-type="indexterm" id="idm46402338027304"/>You just made your console app throw two different kinds of exception—an IndexOutOfRangeException and a FileNotFoundException—and they were both handled. Take a closer look at the <code>catch</code> block:</p>&#13;
<pre data-type="programlisting">    catch (<strong>Exception</strong> ex)</pre>&#13;
<p>This is a <strong>catch-all exception</strong>: the type after the <code>catch</code> block indicates what type of exception to handle, and since all exceptions extend the System.Exception class, specifying <code>Exception</code> as the type tells the <code>try/catch</code> block to catch any exception.</p>&#13;
<section data-pdf-bookmark="Avoid catch-all exception with multiple catch blocks" data-type="sect2"><div class="sect2" id="avoid_catch_all_exception_with_multiple">&#13;
<h2>Avoid catch-all exception with multiple catch blocks</h2>&#13;
<p>It’s always better to try to anticipate the specific exceptions that your code will throw and handle them. For example, we know that this code can throw an IndexOutOfRange exception if no filename is specified, or a FileNotFound exception if an invalid file is found. We also saw earlier in the chapter that trying to read an unreadable file causes the CLR to throw an UnauthorizedAccessException. You can handle these different kinds of exceptions by adding <strong>multiple <code>catch</code> blocks</strong> to your code:</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg637.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p>Now your app will write different error messages depending on which exception is handled. Notice that the first two <code>catch</code> blocks <strong>did not specify a variable name</strong> (like <code>ex</code>). You only need to specify a variable name if you’re going to use the Exception object.</p>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="brain_power-idd0030">&#13;
<h5><span class="inlineimage"><img alt="Images" src="assets/brainpower.png"/></span> Brain Power</h5>&#13;
<p>Can any of these exceptions be <em><strong>prevented</strong></em> rather than handled?</p>&#13;
</div></aside>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="there_are_no_dumb_questions-idd0041">&#13;
<h5>there are no Dumb Questions</h5>&#13;
<p><a data-primary="catch blocks" data-secondary="with no specified exceptions" data-type="indexterm" id="idm46402338009736"/><a data-primary="debugger" data-secondary="catch blocks" data-type="indexterm" id="idm46402338008408"/><a data-primary="exception handling" data-secondary="catching specific exception types" data-type="indexterm" id="idm46402338007256"/><a data-primary="exception handling" data-secondary="handled versus unhandled exceptions" data-type="indexterm" id="idm46402338006184"/><a data-primary="exception handling" data-secondary="program stopping with exceptions" data-type="indexterm" id="idm46402338005064"/><a data-primary="null reference" data-type="indexterm" id="idm46402338003992"/><a data-primary="unhandled exceptions" data-type="indexterm" id="idm46402338003112"/><strong>Q: Back up a second. So every time my program runs into an exception, it’s going to stop whatever it’s doing unless I specifically write code to catch it? How is that a good thing?</strong></p>&#13;
<p><strong>A:</strong> One of the best things about exceptions is that they make it obvious when you run into problems. Imagine how easy it could be in a complex application for you to lose track of all of the objects your program was working with. Exceptions call attention to your problems and help you root out their causes so that you always know that your program is doing what it’s supposed to do.</p>&#13;
<p>Any time an exception occurs in your program, something you expected to happen didn’t. Maybe an object reference wasn’t pointing where you thought it was, or a user supplied a value you hadn’t considered, or a file you thought you’d be working with suddenly isn’t available. If something like that happened and you didn’t know it, it’s likely that the output of your program would be wrong, and the behavior from that point on would be pretty different from what you expected when you wrote the program.</p>&#13;
<p>Now imagine that you had no idea the error had occurred and your users started calling you up and telling you that your program was unstable. That’s why it’s a good thing that exceptions disrupt everything your program is doing. They force you to deal with the problem while it’s still easy to find and fix.</p>&#13;
<p><strong>Q: Remind me again—what do I use the Exception object for?</strong></p>&#13;
<p><strong>A:</strong> The Exception object gives you clues about what went wrong. You can use its type to determine what kind of problem happened, and write an exception handler to deal with it in a way that keeps your app running.</p>&#13;
<p><strong>Q: What’s the difference between a <strong><em>handled</em></strong> exception and an <strong><em>unhandled</em></strong> exception?</strong></p>&#13;
<p><strong>A:</strong> Whenever your program throws an exception, the runtime environment will search through your code looking for a <code>catch</code> block that handles it. If you’ve written one, the <code>catch</code> block will execute and do whatever you specified for that particular exception. Since you wrote a <code>catch</code> block to deal with that error up front, that exception is considered handled.</p>&#13;
<p>If the runtime can’t find a <code>catch</code> block that matches the exception, it stops everything your program is doing and raises an error. That’s an <em>unhandled</em> exception.</p>&#13;
<p><strong>Q: What happens when you have a <code>catch</code> that doesn’t specify a particular exception?</strong></p>&#13;
<p><strong>A:</strong> That’s called a <strong>catch-all exception</strong>. A <code>catch</code> block like that will catch any kind of exception the <code>try</code> block can throw. So if you don’t need to declare a variable to use the Exception object, an easy way to write a catch-all exception is like this:</p>&#13;
<pre data-type="programlisting">catch  &#13;
{ &#13;
   <span style="color:#9D9EA0;">// handle the exception</span>&#13;
}</pre>&#13;
<p><strong>Q: Isn’t it easier to use a catch-all exception? Isn’t it safer to write code that always catches every exception?</strong></p>&#13;
<p><strong>A:</strong> You should <strong>always do your best to avoid catching Exception</strong>, and instead catch specific exceptions. You know that old saying about how an ounce of prevention is better than a pound of cure? That’s especially true in exception handling. Depending on catch-all exceptions is usually just a way to make up for bad programming. For example, you’re often better off using File.Exists to check for a file before you try to open it than catching a FileNotFoundException. While some exceptions are unavoidable, you’ll find that a surprising number of them never have to be thrown in the first place.</p>&#13;
<p><strong>Q: If a <code>catch</code> block with no specified exception will catch anything, why would I ever want to specify an exception type?</strong></p>&#13;
<p><strong>A:</strong> Certain exceptions might require different actions to keep your program moving. Maybe an exception caused by dividing by zero might have a <code>catch</code> block where it goes back and sets properties to save some of the data you’ve been working with, while a null reference exception in the same block of code might require it to create new instances of an object.</p>&#13;
<blockquote>&#13;
<p><strong>An unhandled exception can cause your program to run <span style="color:#9D9EA0;">unpredictably</span>. That’s why the program stops whenever it runs into one.</strong></p>&#13;
</blockquote>&#13;
</div></aside>&#13;
</div></section>&#13;
</div></section>&#13;
<section data-pdf-bookmark="Pool Puzzle" data-type="sect1"><div class="sect1" id="pool_puzzle-idd0004">&#13;
<h1>Pool Puzzle</h1>&#13;
<p>Your <strong><em>job</em></strong> is to take code snippets from the pool and place them into the blank lines in the program. You can use the same snippet more than once, and you won’t need to use all the snippets. Your <strong><em>goal</em></strong> is to make the program produce the output below.</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg639.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
</div></section>&#13;
<section data-pdf-bookmark="Pool Puzzle Solution" data-type="sect1"><div class="sect1" id="pool_puzzle_solution-idd0004">&#13;
<h1>Pool Puzzle Solution</h1>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg640.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg641-1.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p><strong>Unhandled exceptions <span style="color:#9D9EA0;">bubble up.</span></strong></p>&#13;
<p><a data-primary="bubble up" data-type="indexterm" id="idm46402337968408"/><a data-primary="constructors" data-secondary="exceptions in" data-type="indexterm" id="idm46402337967416"/><a data-primary="exception handling" data-secondary="exceptions in constructors" data-type="indexterm" id="idm46402337966296"/>Believe it or not, it can be really useful to leave exceptions unhandled. Real-life programs have complex logic, and it’s often difficult to recover correctly when something goes wrong, especially when a problem occurs very far down in the program. By only handling specific exceptions and avoiding catch-all exception handlers, you let unexpected exceptions <strong><em>bubble up</em></strong>: instead of being handled in the current method, they’re caught by the next statement up the call stack. Anticipating and handling the exceptions that you expect and letting unhandled exceptions bubble up is a great way to build more robust apps.</p>&#13;
<p>Sometimes it’s useful to <strong>rethrow</strong> an exception, which means that you handle an exception in a method but <em>still bubble it up</em> to the statement that called it. All you need to do to rethrow an exception is call <code>throw;</code> inside a <code>catch</code> block, and the exception that it caught will immediately bubble up:</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg641-2.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<div data-type="note" epub:type="note"><h6>Note</h6>&#13;
<p><span style="color:#9D9EA0;">Here’s a career tip: a lot of C# programming job interviews include a question about how you deal with exceptions in a constructor.</span></p>&#13;
</div>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="watch_itexclamation_mark-idd0014">&#13;
<h5><span class="inlineimage"><img alt="Images" src="assets/watchit.png"/></span> Watch it!</h5>&#13;
<p><strong>Keep risky code out of the constructor!</strong></p>&#13;
<p><em>You’ve noticed by now that a constructor doesn’t have a return value, not even void. That’s because a constructor doesn’t actually return anything. Its only purpose is to initialize an object— which is a problem for exception handling inside the constructor. When an exception is thrown inside the constructor, then the statement that tried to instantiate the class <strong>won’t end up with an instance of the object</strong></em>.</p>&#13;
</div></aside>&#13;
</div></section>&#13;
<section data-pdf-bookmark="Use the right exception for the situation" data-type="sect1"><div class="sect1" id="use_the_right_exception_for_the_situatio">&#13;
<h1>Use the right exception for the situation</h1>&#13;
<p><a data-primary="NotImplementedException" data-type="indexterm" id="idm46402337947784"/><a data-primary="System.Exception" data-type="indexterm" id="idm46402337952632"/>When you use the IDE to generate a method, it adds code that looks like this:</p>&#13;
<pre data-type="programlisting">   private void MyGeneratedMethod()&#13;
   {&#13;
       throw new NotImplementedException();&#13;
   }</pre>&#13;
<p>The <strong>NotImplementedException</strong> is used any time you have an operation or method that hasn’t been implemented. It’s a great way to add a placeholder—as soon as you see one you know there’s code that you need to write. That’s just one of the many exceptions that .NET provides.</p>&#13;
<p>Choosing the right exception can make your code easier to read, and make exception handling cleaner and more robust. For example, code in a method that validates its parameters can throw an ArgumentException, which has an overloaded constructor with a parameter to specify which argument caused the problem. Consider the Guy class back in <a href="ch03.html#objectshellipget_orientedexclamation_mar">#objectshellipget_orientedexclamation_mar</a>, had a ReceiveCash method that checked the <code>amount</code> parameter to make sure it was receiving a positive amount. This is a good opportunity to throw an ArgumentException:</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg642-1.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p>Take a minute and look over the list of exceptions that are part of the .NET API—you can throw any of them in your code: <a href="https://docs.microsoft.com/en-us/dotnet/api/system.systemexception">https://docs.microsoft.com/en-us/dotnet/api/system.systemexception</a>.</p>&#13;
<section data-pdf-bookmark="Catch custom exceptions that extend System.Exception" data-type="sect2"><div class="sect2" id="catch_custom_exceptions_that_extend_syst">&#13;
<h2>Catch custom exceptions that extend System.Exception</h2>&#13;
<p>Sometimes you want your program to throw an exception because of a special condition that could happen when it runs. Let’s go back to the Guy class from <a href="ch03.html#objectshellipget_orientedexclamation_mar">#objectshellipget_orientedexclamation_mar</a>. Suppose you’re using it in an app that absolutely depended on a Guy always having a positive amount of cash. You could add a custom exception that <strong>extends System.Exception</strong>:</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg642-2.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p>Now you can throw that new exception, and catch it exactly like you’d catch any other exception:</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg642-3.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
</div></section>&#13;
</div></section>&#13;
<section data-pdf-bookmark="Exception Magnets" data-type="sect1"><div class="sect1" id="exception_magnets">&#13;
<h1>Exception Magnets</h1>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/Common-11.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p>Arrange the magnets so the application writes the following output to the console:</p>&#13;
<p><strong>when it thaws it throws.</strong></p>&#13;
<pre data-type="programlisting">class Program {&#13;
   public static void Main(string[] args) {&#13;
       Console.Write("when it ");&#13;
       ExTestDrive.Zero("yes");&#13;
       Console.Write(" it ");&#13;
       ExTestDrive.Zero("no");&#13;
       Console.WriteLine(".");&#13;
   }&#13;
}&#13;
&#13;
class MyException : Exception { } </pre>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg643.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
</div></section>&#13;
<section data-pdf-bookmark="Exception Magnets Solution" data-type="sect1"><div class="sect1" id="exception_magnets_solution">&#13;
<h1>Exception Magnets Solution</h1>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/Common-11.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p>Arrange the magnets so the application writes the following output to the console:</p>&#13;
<p><strong>when it thaws it throws.</strong></p>&#13;
<pre data-type="programlisting">class Program {&#13;
   public static void Main(string[] args) {&#13;
       Console.Write("when it ");&#13;
       ExTestDrive.Zero("yes");&#13;
       Console.Write(" it ");&#13;
       ExTestDrive.Zero("no");&#13;
       Console.WriteLine(".");&#13;
   }&#13;
}</pre>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg644.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="behind_the_scenes-idd0006">&#13;
<h5><span class="inlineimage"><img alt="Images" src="assets/icon5.png"/></span> Behind the Scenes</h5>&#13;
<p><a data-primary="Dispose() method" data-secondary="calling" data-type="indexterm" id="idm46402337917032"/><a data-primary="IDisposable interface" data-secondary="try/finally and" data-type="indexterm" id="idm46402337915688"/><strong>IDisposable uses try/finally to ensure the Dispose method is called</strong></p>&#13;
<p>Remember when we sleuthed out this code from <a href="ch10.html#reading_and_writing_files_save_the_last">#reading_and_writing_files_save_the_last</a>?</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg645-1.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p>We were exploring how <code>using</code> statements work, and in this case we needed to nest one <code>using</code> statement inside the other to make sure the StreamWriter was disposed of before the MemoryStream. We did that because both the StreamWriter and MemoryStream classes implement the IDisposable interface and put a call to their Close method inside their Dispose method. Each <code>using</code> statement makes sure the Dispose method is called at the end of its block, and that ensures the streams are always closed.</p>&#13;
<p>Now that you’ve been working with exception handling, you can see how the <code>using</code> statement works. The <code>using</code> statement is an example of <strong>syntactic sugar</strong>: a way that C# “sweetens” the language by giving you a convenient shortcut that makes your code easier to read. When you do this, it’s actually a kind of shortcut:</p>&#13;
<pre data-type="programlisting">            using (var sw = new StreamWriter(ms))&#13;
            {&#13;
                sw.WriteLine("The value is {0:0.00}", 123.45678);&#13;
            }</pre>&#13;
<p>The C# compiler actually generates compiled code that looks (approximately) like this:</p>&#13;
<pre data-type="programlisting">            <strong>try</strong> {&#13;
                var sw = new StreamWriter(ms))&#13;
                sw.WriteLine("The value is {0:0.00}", 123.45678); &#13;
            } <strong>finally</strong> {&#13;
                sw.Dispose();&#13;
            }</pre>&#13;
<p>Putting the Dispose statement in a <code>finally</code> block makes sure that it’s always run—even if an exception occurs.</p>&#13;
<blockquote>&#13;
<p><strong>IDisposable is a great tool for avoiding exceptions.</strong></p>&#13;
</blockquote>&#13;
</div></aside>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg645-2.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
</div></section>&#13;
<section data-pdf-bookmark="Exception filters help you create precise handlers" data-type="sect1"><div class="sect1" id="exception_filters_help_you_create_precis">&#13;
<h1>Exception filters help you create precise handlers</h1>&#13;
<p><a data-primary="exception handling" data-secondary="filters and" data-type="indexterm" id="idm46402337898568"/>Let’s say we’re building a game set in classic 1930s mafia gangland, and we’ve got a LoanShark class that needs to collect cash from instances of Guy using the Guy.GiveCash method, and that handles any OutOfCashException with a good old gangland-style lesson.</p>&#13;
<p>The thing is, every loan shark knows the golden rule: don’t try to collect money from the big mob boss. That’s where <strong>exception filters</strong> can come in really handy. An exception filter uses the <code>when</code> keyword to tell your exception handler to catch an exception only under specific conditions.</p>&#13;
<p>Here’s an example of how an exception filter works:</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg646-1.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg646-2.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg646-3.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p><strong>It’s always better to build the most precise exception handlers that we can.</strong></p>&#13;
<p>There’s more to exception handling than just printing out a generic error message. Sometimes you want to handle different exceptions differently—like how the hex dumper handled a FileNotFoundException differently from an UnauthorizedAccessException. Planning for exceptions always involves <strong><em>unexpected situations</em></strong>. Sometimes those situations can be prevented, sometimes you want to handle them, and sometimes you want the exceptions to bubble up. A big lesson to learn here is that there’s no “one-size-fits-all” approach to dealing with the unexpected, which is why the IDE doesn’t just wrap everything in a <code>try/catch</code> block.</p>&#13;
<div data-type="note" epub:type="note"><h6>Note</h6>&#13;
<p><span style="color:#9D9EA0;">This is why there are so many classes that inherit from Exception, and why you may even want to write your own classes to inherit from Exception.</span></p>&#13;
</div>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="there_are_no_dumb_questions-idd0042">&#13;
<h5>there are no Dumb Questions</h5>&#13;
<p><a data-primary="Dispose() method" data-seealso="IDisposable interface" data-type="indexterm" id="idm46402337884264"/><a data-primary="Dispose() method" data-secondary="calling" data-type="indexterm" id="idm46402337885848"/><a data-primary="finally block" data-type="indexterm" id="idm46402337879848"/><a data-primary="IDisposable interface" data-type="indexterm" id="idm46402337879016"/><a data-primary="IDisposable interface" data-secondary="about" data-type="indexterm" id="idm46402337878184"/><a data-primary="try/finally block" data-seealso="exception handling" data-type="indexterm" id="idm46402337877048"/><a data-primary="using statements" data-type="indexterm" id="idm46402337875976"/><strong>Q: I’m still not clear on when I should be catching exceptions, when I should be preventing them, and when I should let them bubble up.</strong></p>&#13;
<p><strong>A:</strong> That’s because there’s no single correct answer, or a rule that you can follow in every situation—it always depends on what you want your code to do.</p>&#13;
<p>Actually, that’s not 100% true. There is a rule: it’s always better to prevent exceptions if you can. You can’t always anticipate the unexpected, especially when you’re dealing with input from users or decisions they make.</p>&#13;
<p>Deciding whether to let exceptions bubble up or handle them in the class often boils down to separation of concerns. Does it make sense for a class to know about a certain exception? It depends on what that class does. Luckily, the IDE’s refactoring tools are always there to help you change your code if you decide that certain exceptions are better off bubbled up than caught.</p>&#13;
<p><strong>Q: Can you explain what you meant by “syntactic sugar?”</strong></p>&#13;
<p><strong>A:</strong> When developers use the term <em>syntactic sugar</em>, they’re typically talking about a programming language giving you a convenient and easy-to-understand shortcut for code that would otherwise be more complex. The word “syntax” refers to the keywords of C# and the rules that govern them. The using statement is an official part of the C# syntax, which has rules that say that it must be followed by a variable declaration that instantiates a type that implements IDisposable, followed by a block of code. The “sugar” part refers to the fact that it’s <em>super sweet</em> that the C# compiler turns it into something that would be much clunkier if you had to write it out by hand.</p>&#13;
<p><strong>Q: Is it possible to use an object with a <code>using</code> statement if it doesn’t implement IDisposable?</strong></p>&#13;
<p><strong>A:</strong> No. You can only create objects that implement IDisposable with <code>using</code> statements, because they’re tailor-made for each other. Adding a <code>using</code> statement is just like creating a new instance of a class, except that it always calls its Dispose method at the end of the block. That’s why the class <strong>must implement</strong> the IDisposable interface.</p>&#13;
<p><strong>Q: Can you put any statement inside a <code>using</code> block?</strong></p>&#13;
<p><strong>A:</strong> Definitely. The whole idea with <code>using</code> is that it helps you make sure that every object you create with it is disposed of. But what you do with those objects is entirely up to you. In fact, you can create an object with a <code>using</code> statement and never even use it inside the block. That would be pretty useless, though, so we don’t recommend doing that.</p>&#13;
<p><strong>Q: Can you call the Dispose method outside of a <code>using</code> statement?</strong></p>&#13;
<p><strong>A:</strong> Yes. You don’t ever actually <strong><em>need</em></strong> to use a <code>using</code> statement. You can call Dispose yourself when you’re done with the object, or manually do whatever cleanup is necessary—like calling a stream’s Close method, which you did in <a href="ch10.html#reading_and_writing_files_save_the_last">#reading_and_writing_files_save_the_last</a>. If you use a <code>using</code> statement, it’ll make your code easier to understand and prevent problems that happen if you don’t dispose of your objects.</p>&#13;
<p><strong>Q: Since a <code>using</code> statement basically generates a <code>try/catch</code> block that calls the Dispose method, is it OK to do exception handling inside of the <code>using</code> block?</strong></p>&#13;
<p><strong>A:</strong> Yes. It works exactly like the nested <code>try/catch</code> blocks that you used earlier in the chapter in your GetInputStream method.</p>&#13;
<p><strong>Q: You mentioned a <code>try/finally</code> block. Does that mean it’s OK to have a <code>try</code> and <code>finally</code> without a <code>catch</code>?</strong></p>&#13;
<p><strong>A:</strong> Yes! You can definitely have a <code>try</code> block without a <code>catch</code>, and just a <code>finally</code>. It looks like this:</p>&#13;
<pre data-type="programlisting">try&#13;
 {&#13;
     DoSomethingRisky();&#13;
     SomethingElseRisky();&#13;
}&#13;
finally {&#13;
     AlwaysExecuteThis();&#13;
}</pre>&#13;
<p>If DoSomethingRisky throws an exception, then the <code>finally</code> block will immediately run.</p>&#13;
<p><strong>Q: Does Dispose only work with files and streams?</strong></p>&#13;
<p><strong>A:</strong> Not at all. There are a lot of classes that implement IDisposable, and when you’re using one you should always use a <code>using</code> statement. If you write a class that has to be disposed of in a certain way, then you can implement IDisposable, too.</p>&#13;
<blockquote>&#13;
<p><strong>There’s no one-size-fits-all approach to planning for the unexpected.</strong></p>&#13;
</blockquote>&#13;
</div></aside>&#13;
</div></section>&#13;
<section data-pdf-bookmark="The worst catch block EVER: catch-all plus comments" data-type="sect1"><div class="sect1" id="the_worst_catch_block_ever_catch_all_plu">&#13;
<h1>The worst catch block <u>EVER</u>: catch-all plus comments</h1>&#13;
<p><a data-primary="catch blocks" data-secondary="letting your program keep running" data-type="indexterm" id="idm46402337844792"/><a data-primary="exception handling" data-secondary="handling, not burying" data-type="indexterm" id="idm46402337843464"/>A <code>catch</code> block will let your program keep running if you want it to. An exception gets thrown, you catch the exception, and instead of shutting down and giving an error message, you keep going. But sometimes, that’s not such a good thing.</p>&#13;
<p>Take a look at this <code>Calculator</code> class, which seems to be acting funny all the time. What’s going on?</p>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg648.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<section data-pdf-bookmark="You should handle your exceptions, not bury them" data-type="sect2"><div class="sect2" id="you_should_handle_your_exceptionscomma_n">&#13;
<h2>You should <u>handle</u> your exceptions, not <u>bury</u> them</h2>&#13;
<p>Just because you can keep your program running doesn’t mean you’ve <em>handled</em> your exceptions. In the code above, the calculator won’t crash...at least, not in the Divide method. What if some other code calls that method, and tries to print the results? If the divisor was zero, then the method probably returned an incorrect (and unexpected) value.</p>&#13;
<p>Instead of just adding a comment and burying the exception, you need to <strong>handle the exception</strong>. If you’re not able to handle the problem, <strong><em>don’t leave empty or commented <code>catch</code> blocks!</em></strong> That just makes it harder for someone else to track down what’s going on. It’s better to let the program continue to throw exceptions, because then it’s easier to figure out what’s going wrong.</p>&#13;
<div data-type="note" epub:type="note"><h6>Note</h6>&#13;
<p><span style="color:#9D9EA0;">Remember, when your code doesn’t handle an exception, the exception bubbles up the call stack. Letting an exception bubble up is a perfectly valid way of dealing with an exception, and in some cases it makes more sense to do that than to use an empty catch block to bury the exception.</span></p>&#13;
</div>&#13;
</div></section>&#13;
</div></section>&#13;
<section data-pdf-bookmark="Temporary solutions are OK (temporarily)" data-type="sect1"><div class="sect1" id="temporary_solutions_are_ok_left_parenthe">&#13;
<h1>Temporary solutions are OK (temporarily)</h1>&#13;
<p><a data-primary="exception handling" data-secondary="handling versus fixing" data-type="indexterm" id="idm46402337831544"/>Sometimes you find a problem, and know it’s a problem, but aren’t sure what to do about it. In these cases, you might want to log the problem and note what’s going on. That’s not as good as handling the exception, but it’s better than doing nothing.</p>&#13;
<p>Here’s a temporary solution to the calculator problem:</p>&#13;
<div data-type="note" epub:type="note"><h6>Note</h6>&#13;
<p><span style="color:#9D9EA0;">...but in real life, “temporary” solutions have a nasty habit of becoming permanent.</span></p>&#13;
</div>&#13;
<div data-type="note" epub:type="note"><h6>Note</h6>&#13;
<p><strong>Take a minute and think about this <code>catch</code> block. What happens if the <code>StreamWriter</code> can’t write to the C:\Logs\ folder? You can <span style="color:#9D9EA0;">nest</span> another <code>try/catch</code> block inside it to make it <span style="color:#9D9EA0;">less risky</span>. Can you think of a better way to do this?</strong></p>&#13;
</div>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg649-1.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<figure class="informal"><div class="figure">&#13;
<img alt="Images" src="assets/pg649-2.png"/>&#13;
<h6/>&#13;
</div></figure>&#13;
<p><strong>Handling exceptions doesn’t always mean the same thing as FIXING exceptions.</strong></p>&#13;
<p>It’s never good to have your program bomb out. It’s way worse to have no idea why it’s crashing or what it’s doing to users’ data. That’s why you need to be sure that you’re always dealing with the errors you can predict and logging the ones you can’t. While logs can be useful for tracking down problems, preventing those problems in the first place is a better, more permanent solution.</p>&#13;
<aside data-type="sidebar" epub:type="sidebar"><div class="sidebar" id="bullet_points-idd0027">&#13;
<h5>Bullet Points</h5>&#13;
<ul>&#13;
<li><p><a data-primary="ArgumentException" data-type="indexterm" id="idm46402337813576"/><a data-primary="catch blocks" data-secondary="about" data-type="indexterm" id="idm46402337812360"/><a data-primary="debugger" data-secondary="Bullet Points" data-type="indexterm" id="idm46402337811208"/><a data-primary="exception handling" data-type="indexterm" id="idm46402337810024"/><a data-primary="exception handling" data-secondary="Bullet Points" data-type="indexterm" id="idm46402337808712"/><a data-primary="NullReferenceException (NRE)" data-type="indexterm" id="idm46402337807672"/><a data-primary="throw, using to rethrow exceptions" data-type="indexterm" id="idm46402337806808"/><a data-primary="try blocks" data-seealso="exception handling" data-type="indexterm" id="idm46402337806040"/>Any statement can throw an <strong>exception</strong> if something fails at <strong>runtime</strong> (or while the code is running).</p></li>&#13;
<li><p>Use a <code><strong>try/catch</strong></code> block to handle exceptions. Unhandled exceptions will cause your program to stop execution and pop up an error window.</p></li>&#13;
<li><p>Any exception in the block of code after the <code>try</code> statement will cause the program’s execution to immediately jump to the first statement in the <strong>exception handler</strong>, or the block of code after <code>catch</code>.</p></li>&#13;
<li><p>The <strong>Exception object</strong> gives you information about the exception that was caught. If you specify an Exception variable in your <code>catch</code> statement, that variable will contain information about any exception thrown in the <code>try</code> block:</p>&#13;
<pre data-type="programlisting">   try {&#13;
     // statements that might&#13;
     // throw exceptions&#13;
   } catch (IOException ex) {&#13;
     // if an exception is thrown,&#13;
     // ex has information about it    &#13;
   }</pre></li>&#13;
<li><p>There are many <strong>different kinds of exceptions</strong> that you can catch. Each has its own object that extends System.Exception.</p></li>&#13;
<li><p>Try to avoid <strong>catch-all exception handlers</strong> just catching Exception. Handle specific exceptions instead.</p></li>&#13;
<li><p>A <code><strong>finally</strong></code> <strong>block</strong> after the exception handlers will always run whether or not an exception is thrown.</p></li>&#13;
<li><p>Each <code>try</code> can have more than one <code>catch</code>:</p>&#13;
<pre data-type="programlisting">   try { ... }&#13;
   catch (NullReferenceException ex) {&#13;
      // these statements will run if a&#13;
      // NullReferenceException is thrown&#13;
    }   &#13;
    catch (OverflowException ex) { ... }&#13;
    catch (FileNotFoundException) { ... }&#13;
    catch (ArgumentException) { ... }</pre></li>&#13;
<li><p>Your code can <strong>throw an exception</strong> using <code>throw</code>:</p>&#13;
<pre data-type="programlisting">   throw new Exception("Exception message");</pre></li>&#13;
<li><p>Your code can also <strong>rethrow</strong> an exception using <code>throw;</code> but this only works inside of a <code>catch</code> block. Rethrowing an exception preserves the call stack.</p></li>&#13;
<li><p>You can create a <strong>custom exception</strong> by adding a class that extends the System.Exception base class:</p>&#13;
<pre data-type="programlisting">   class CustomException : Exception { }</pre></li>&#13;
<li><p>Most of the time, you only need to throw exceptions that are built into .NET, like <code>ArgumentException</code>. One reason to use different kinds of exceptions is to <strong>give more information</strong> to people troubleshooting problems.</p></li>&#13;
<li><p>An <strong>exception filter</strong> uses the <code>when</code> keyword to tell your exception handler to catch an exception only under specific conditions.</p></li>&#13;
<li><p>The <code>using</code> statement is <strong>syntactic sugar</strong> that causes the C# compiler to generate the equivalent of a <code>finally</code> block that calls the Dispose method.</p></li>&#13;
</ul>&#13;
</div></aside>&#13;
</div></section>&#13;
&#13;
</div></section></body></html>